### ISSUE TITLE
Unable to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by nicklaw5** [davidworkman9/drawingtotext#5]
OS: Ubuntu 16.04

After successfully installing dxflib, running `make` from within the root of this project throws this error:
```
ubuntu@fm-dev:/tmp/drawingtotext$ sudo make
g++ -ggdb -o drawingtotext OutputFormatText.cpp OutputFormatConsole.cpp OutputFormatTypes.cpp InputFormatDXF.cpp GetInsertions.cpp InputFormatDWG.cpp AutoCADConverter.cpp -ldxflib -I/usr/include/gdal -lredwg
/tmp/ccsMEcLL.o: In function `InputFormatDXF::InputFormatDXF(char const*)':
/tmp/drawingtotext/InputFormatDXF.cpp:7: undefined reference to `DL_Dxf::in(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DL_CreationInterface*)'
/tmp/ccsMEcLL.o: In function `InputFormatDXF::readFeaturesInto(OutputFormat*)':
/tmp/drawingtotext/InputFormatDXF.cpp:34: undefined reference to `DL_Dxf::in(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DL_CreationInterface*)'
collect2: error: ld returned 1 exit status
Makefile:2: recipe for target 'drawingtotext' failed
make: *** [drawingtotext] Error 1
```

**Comment by darkworks** [comment]
same here , hate this shitty lib
